### ISSUE TITLE
The interactivity of the essay (index_old.html) is broken.

### ISSUE THREAD

**Issue by wizzwizz4** [ncase/simulating#13]
The redirects don't preserve the model id (or the "preview only" mode for the header bar thing), so [everything just displays forest fires](https://ncase.me/simulating/index_old.html). That means your lovely words are just words! :open_mouth: I'd really like to keep being able to link this to people, but it isn't functioning properly at the moment.

**Comment by ncase** [comment]
I didn't know folks still liked the old version, let alone wanted to visit it! I have corrected that –– now instead of an auto-direct, it lets you visit the old version (you may need to refresh cache/page for the old models to load again)

<img width="614" alt="asd" src="https://user-images.githubusercontent.com/825858/71849732-c5d20f00-30a0-11ea-8ac5-37e75e1fa74d.png">

Thank you for catching this! 👍
